### ISSUE TITLE
Please do not use the elementary name

### ISSUE THREAD

**Issue by cassidyjames** [krisives/elementary-os-extras#1]
We already have enough issues with people thinking the old “elementary Tweaks” was something official or made by elementary—which is why it was rebranded by its developer to “Pantheon Tweaks.” Creating a new project under the elementary name that is not made by elementary is inviting similar issues and could contribute to dilution of the elementary brand and trademarks.

https://elementary.io/brand

Please rename this project to something that does not include the elementary name to avoid similar issues.

**Comment by krisives** [comment]
Hi @cassidyjames thanks for voicing your concerns.

Why do you think this is different than how Ubuntu works? Similarly there are many Ubuntu tools that use it in their name and nobody seems to be confused about that and to my knowledge Canonical has not voiced any such concerns - if anything they seem to embrace the open use of the name.

**Comment by cassidyjames** [comment]
I can't hypothesize on another company's trademarks other than pointing out that they legally require explicit written approval to use the term "Ubuntu" according to their own legal documentation: https://ubuntu.com/legal/intellectual-property-policy#your-use-of-our-trademarks

**Comment by krisives** [comment]
Thanks @cassidyjames!

I have two questions:

1. Do you have an alternative name suggestion? The situation with Pantheon Tweaks is a bit different and calling this Pantheon Extras doesn't seem to make a lot of sense. Also, IMO, that really only moves the problem slightly to the left because there is nothing stopping elementary (or another company) from trademarking Pantheon. That seems like turtles all the way down.

2. Is there actually a current trademark currently registered for elementary? I found trademark serial number `86602730` which was once registered but seems to have expired nearly half a decade ago.

Thanks again for your help.

**Comment by cassidyjames** [comment]
1. Something like `Extras for elementary OS` is usually the recommendation if you want to be able to use/associate with `elementary OS` but want to ensure it's not going to be confused as something official. See the same situation with Reddit apps being called e.g. `Sync for Reddit` instead of `Reddit Sync`.

2. I am not a lawyer and don't have the exact details on hand but would be happy to have someone follow up if you want to email brand@elementary.io. Regardless, trademarks that are used in commerce (as `elementary` is) don't actually require registration to be considered a valid trademark and to gain certain protections under US law. Again, I am not a lawyer but would be happy to have someone follow up via email.

**Comment by krisives** [comment]
Thanks @cassidyjames.

1. In the case of Reddit they specifically give that permission in their trademarks, whereas `elementary.io/brand` states `but do not use the elementary name or marks as part of the name of your company, application, product, or service—or in any logo you create.` So that doesn't seem compatible.

2. I'm a bit confused. The previous expired trademark application `86602730` was filed by the company you incorporated in Iowa, which at the time was `Elementary, LLC`. Basically, has there been a newer trademark application since that one expired in 2016? My understanding is that this mark needs to be renewed every 5th and 10th year, which it was not?

**Comment by cassidyjames** [comment]
>I am not a lawyer and don't have the exact details on hand but would be happy to have someone follow up if you want to email brand@elementary.io. Regardless, trademarks that are used in commerce (as elementary is) don't actually require registration to be considered a valid trademark and to gain certain protections under US law. Again, I am not a lawyer but would be happy to have someone follow up via email.

**Comment by krisives** [comment]
Let me know when you find time to address the conflict for (1)

**Comment by krisives** [comment]
@cassidyjames I actually looked closer at this issue and there may be a bigger problem. As far as I can tell regarding application `86602730` the USPTO specifically refused to grant the mark:

[86602730.pdf](https://github.com/krisives/elementary-os-extras/files/7079102/86602730.pdf)

The relevant part here is:

> REFUSAL – TITLE OF A SINGLE WORK
> 
> Registration is refused because the applied-for mark, as used on the specimen of record (1) is used only as the title of a single creative work, namely, the title of a specific CD; and (2) does not function as a trademark to indicate the source of applicant’s goods and to identify and distinguish them from others.  Trademark Act Sections 1, 2, and 45, 15 U.S.C. §§1051-1052, 1127; see Herbko Int’l, Inc. v. Kappa Books, Inc., 308 F.3d 1156, 1162-63, 64 USPQ2d 1375, 1378-79 (Fed. Cir. 2002); In re Cooper, 254 F.2d 611, 615-16, 117 USPQ 396, 399-400 (C.C.P.A. 1958); TMEP §§904.07(b), 1202.08.  

As far as I can tell you do not currently and have never been granted the trademark.

**Comment by cassidyjames** [comment]
@krisives we cover the "for elementary OS" bit on the brand page:

https://elementary.io/brand#community

>**You are encouraged to say that your app or service is “designed for elementary OS,”** but do not use the elementary name or marks as part of the name of your company, application, product, or service—or in any logo you create.

I can raise an issue with the team to see if that can be further clarified, but for now I can just direct you to the language used there.

Further, I would appreciate if you stop digging up random legal documents and effectively doxing me on a public GitHub thread, hence why I repeatedly asked you to take this up with someone at elementary via email. I am not going to discuss the specifics of legal documents here, especially when they aren't even directly relevant. elementary, Inc. claims the trademark to `elementary` and is actively using it in commerce, which affords certain protections under US trademark law and has enabled elementary to prevent people from distributing other items under our brand name—but I absolutely do not want to go the legal threat route and that's not what this issue was; this issue is me requesting you respect the elementary name and don't use it for something that is not produced by elementary. Because as we've seen repeatedly in the past, it causes real user confusion about the source and endorsement of software.

**Comment by krisives** [comment]
> Further, I would appreciate if you stop digging up random legal documents 

I don't think these are "random" legal documents, aren't they very much related to the exact claim(s) you initiated?

> doxing me on a public GitHub thread

That's absolutely not what was done and I find the insinuation actually very insulting. What I've done specifically is look up the trademark status that you claim to have!

> this issue is me requesting you respect the elementary name 

Except you attempted to do that by claiming to have *trademarks* that it appears you were specifically refused.

**Comment by brdbkr** [comment]
On the elementary OS "brand" page, it says "[t]he word elementary is a trademark of elementary, Inc. to refer to the company itself" which is apparently untrue? Now that we're throwing around terms like "trademark" this is really the sort of conversation best handled by lawyers.

**Comment by cassidyjames** [comment]
@brdbkr which is what I have politely asked @krisives to do by providing an email address to discuss privately and DM'd them on Slack with no response while they insist continuing the conversation publicly and posting links to social media to draw attention to the issue.
 
At this point I'm going to cease discussing the issue here. Everything I've posted is accurate and I'll stand by it, but clearly there's no room for sensible discussion here.

**Comment by krisives** [comment]
![image](https://user-images.githubusercontent.com/153967/131400965-151c5599-dc52-44ce-9de8-597497eb843c.png)

Haha!

**Comment by krisives** [comment]
Also having a bit of trouble checking that Slack DM:

![image](https://user-images.githubusercontent.com/153967/131401358-ca8f6068-6a01-4a19-ad0b-5a58a81ef9a7.png)

**Comment by AdrianVovk** [comment]
In the US, you can have a trademark "in commerce" that is not registered with the USPTO. It is still a valid trademark and has certain protections

**Comment by nixpulvis** [comment]
This whole thread is stupid. `elementary-os-extras` is clearly related to EOS, so why fight your own users and developers!?

Perhaps request a line near the top of the README linking upstream to the official project.

Sorry I couldn't resist chiming in with my 2 cents.

**Comment by AdrianVovk** [comment]
@nixpulvis It's a software repository/PPA. Adding a PPA from a third party is inherently dangerous. If someone adds this thinking it's official because it has the elementary name in it, they'll have a false sense of security

**Comment by quazi-irfan** [comment]
@krisives The quick ban on elementary slack and reddit is clearly why the discussion needed to happen publicly. Also, not sure why it is a problem to post it on social media if he think he is in right here - as many on the HN readers agreed with him, except the quick jump on legal thread and claiming that as a polite tone.

**Comment by AdrianVovk** [comment]
If one of the creators of the project you're contributing to is politely asking you to change something like this, the respectful thing to do is to just change it. I mean come on `extras-for-elementary-os` isn't any worse than the repo name you have now, and there wouldn't be all this fuss. If this was all for Ubuntu or another player, and they asked you to rename "ubuntu-extras" to something different, would you not? How is this any different?

Pulling up legal documents with little understanding of their ramifications and then accusing said creator of _pretending to own a trademark_ (which, according to US law, they do own - just not a registered one) is just plain disrespectful. 

Also note I'm not affiliated with elementary in any way and quite honestly I don't use/like their product. However, respect is a big part of open source

**Comment by danrabbit** [comment]
@quazi-irfan The ban was enacted after @krisives decided to harass us on social media by claiming that we were threatening legal action against him, which again we very explicitly are not doing even though he keeps trying to steer the conversation to trademark law. Nobody here is a lawyer. Nobody is threatening legal action. It was just a request to avoid user confusion.

**Comment by krisives** [comment]
I've already said once that I don't appreciate being labeled as "doxing" or harassment, so I've deleted your comment claiming that.

**Comment by AdrianVovk** [comment]
@krisives dropping legal documents with someone's private address and then drawing public attention to these documents is doxing. Yes, this information was on the internet already, and if someone knew where to look it could be found. That doesn't make bringing public attention to this information any less of a dox.

**Comment by AdrianVovk** [comment]
ESPECIALLY because this address is 6 years old at this point. It's possible that nobody related to elementary lives there anymore and you just subjected the random new homeowners to mail about something they have nothing to do with.

**Comment by AdrianVovk** [comment]
I thought you wanted this to be a public discussion?

**Comment by quazi-irfan** [comment]
@danrabbit Thanks for the clarification.

I agree that project owners are in the right to ask third party developers to change their name to avoid confusion, but Cassidy's request came across as tone deaf. He was referring to legal protections and how it has enabled elementary to prevent other peoples from doing something. It is not hard to see how it could be interpreted as legal threat - right?

**Comment by TeoTwawki** [comment]
Suggestion: just delete the offending link for now so we can all stop wasting our time with debating what is and is not doxxing. I was understanding with the concern of the original post and onboard with a rename before this became so dramatic with doxxing and banning and whatnot and now I am just unsubscribing to need get anymore notifications.

**Comment by krisives** [comment]
@AdrianVovk Continuing to spam the same thing over and over won't work.

**Comment by danrabbit** [comment]
@quazi-irfan confusion is understandable, which is why we've tried to clarify repeatedly that elementary absolutely does not want to pursue legal action and there was never such threat. Not sure what more we can do than repeat that it was only a request. I guess a lesson to be learned here is not to get baited into trying to answer questions

**Comment by krisives** [comment]
Hey at least this time you responded without falsely accusing others of harassment and doxxing.

**Comment by quazi-irfan** [comment]
@danrabbit Thanks for replying. 

Yes, Cassidy mentioned elementary does not want to peruse legal action but it is mentioned once within multiple comments about the legal protections elementary has and how it gives them certain power to makes these kind of requests.

I'd argue it is a hard pill to swallow for @krisives or any developers who is spending his/her free time to improve something.

**Comment by danrabbit** [comment]
@quazi-irfan im sure this comment will be deleted, but if you follow the thread the repo owner keeps trying to steer the conversation back towards trademark law. The big mistake Cass made in this thread was trying to answer the questions he was being asked. He got baited.

The original intention was never anything more than a personal issue report filed by an individual. It's pretty clear that the repo owner here is trying to create a narrative by posting this thread on social media, making big claims, and then deleting comments.

**Comment by krisives** [comment]
@danrabbit The only comments I have deleted have been ones that accuse me of harassment and doxxing, neither of which I've done at all. I've responded to comments made on this GitHub issue which is in my own repository.

> The big mistake Cass made in this thread was trying to answer the questions he was being asked. He got baited.

Where is the bait? You're acting like I somehow tricked you into this situation or invited it. You guys came to my repository!

>  It's pretty clear that the repo owner here is trying to create a narrative by posting this thread on social media

I think it's an important discussion to have. A friend of mine posted it to HN and I think the discussion overall has been pretty useful. The view elementary OS takes on trademarks and name rights in the scope of FOSS is a bit unique.

> making big claims, and then deleting comments.

I've only made one claim, which is related to the elementary trademark, and I've only deleted comments that accuse me of harassment and doxxing - neither of which I believe are remotely true.

It just doesn't work to claim that I started this entire thing when all of my actions have been *reactive*!

**Comment by quazi-irfan** [comment]
@danrabbit If you are claiming law allows you to make this request then isn't it a natural response to ask more about the law you are trying to enforce?

Also, I do not see Cassidy get baited at all as the [burden of proof](https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)) falls on his shoulder given - he needs to provide sufficient warrant for his position.

**Comment by danrabbit** [comment]
@quazi-irfan neither Cassidy nor I are lawyers and **neither of us are making any legal claims whatsoever**. It was a mistake for Cassidy to attempt to answer questions about his understanding of trademark law. Attempting to answer those questions is in no way related to the informal request to rename this project to something other than our brand name.

**Comment by quazi-irfan** [comment]
@danrabbit I am not doubting your intention, but the message is not there.

**Comment by danrabbit** [comment]
@krisives yeah mate it is harassment to make multiple social media posts claiming that you're under a threat that it's been explicitly clarified multiple times that nobody is making. And it is doxxing to pull up someone's address and post it in public like that and then refuse to take it down. Cass was trying to answer your questions about trademarks in good faith. I'm not gonna make any comments about trademarks. Neither of us are lawyers, it's not something we can say anything about. I'm pretty disappointed because both of us and several other members of the community spent a decent amount of time helping you and answering your questions in Slack. This is a pretty uncool use of day instead of getting to help people and make open source software. That's all I have left to say here.

**Comment by krisives** [comment]
> yeah mate it is harassment to make multiple social media posts claiming that you're under a threat

@danrabbit Where did anyone claim they were under threat? The only post I'm aware of was titled "Linux distro creator tries to enforce a trademark he doesn't own"

> and it is doxxing to pull up someone's address and post it in public like that and then refuse to take it down.

I posted a publicly available document after researching a trademark that was being brought up to me, registered and owned by `Elementary, LLC`. What indication did I have that this was an address that was trying to be kept private?

Also @cassidyjames I have replaced the PDF with a redacted copy of an image for you.

**Comment by codyro** [comment]
> @krisives yeah mate it is harassment to make multiple social media posts claiming that you're under a threat that it's been explicitly clarified multiple times that nobody is making. And it is doxxing to pull up someone's address and post it in public like that and then refuse to take it down. Cass was trying to answer your questions about trademarks in good faith. I'm not gonna make any comments about trademarks. Neither of us are lawyers, it's not something we can say anything about. I'm pretty disappointed because both of us and several other members of the community spent a decent amount of time helping you and answering your questions in Slack. This is a pretty uncool use of day instead of getting to help people and make open source software. That's all I have left to say here.

The attempt at portraying anyone in this situation as a "victim" is a bit obtuse -- especially if it's you and or your company. I'm not sure what you're attempting to achieve by commenting however it seems like you may want to consider legal recourse if you believe you have a legal standing.

**Comment by sudoforge** [comment]
> This whole thread is stupid. `elementary-os-extras` is clearly related to EOS, so why fight your own users and developers!?
> 
> Perhaps request a line near the top of the README linking upstream to the official project.
> 
> _Sorry I couldn't resist chiming in with my 2 cents._

I think you meant to say that this thread is... _elementary_.

**Comment by KuromeSan** [comment]
The fundamental elemental particles ™

**Comment by Dazag** [comment]
For *uck sake, the guy is the owner of the company and is asking you (very politely), to not use the name of the company for a product in relation to that company! Are you still measuring your dick to see if you can get enough momentum from the internet to get away with the name you want? This is childish

**Comment by Dazag** [comment]
If I was him, your code would be banned from the platform, so next time I wouldn't have to loose my time to discuss with "someone" like you, this repository should be dead by tomorrow

**Comment by KuromeSan** [comment]
> For *uck sake, the guy is the owner of the company and is asking you (very politely), to not use the name of the company for a product in relation to that company! Are you still measuring your dick to see if you can get enough momentum from the internet to get away with the name you want? This is childish

Fuck trademark and copyright laws. Call it whatever you want.

**Comment by Dazag** [comment]
If I make a distro like his possible, famous and well accepted, where people like you could come and sell or give for free your software, I don't think that I would be asking a lot from you, if I am asking you to cooperate for the welfare of the OS and so for, the welfare of your code. So by neglecting his request, you are just showing yourself by your true colors. You don't care about the OS, nor the distro but your dick (code) and shitty morals and ethics.

**Comment by julianxhokaxhiu** [comment]
> If I make a distro like his possible, famous and well accepted, where people like you could come and sell or give for free your software, I don't think that I would be asking a lot from you, if I am asking you to cooperate for the welfare of the OS and so for, the welfare of your code. So by neglecting his request, you are just showing yourself by your true colors. You don't care about the OS, nor the distro but your dick (code) and shitty morals and ethics.

You clearly have never understood what working on FOSS means. If you think people are "using others" to became famous, then we should all start being doing what Torvalds, Stallman and the founders people tells us to do, because all in all they are the ones who kickstarted this whole thing.

Guess what? World is much more complex than that and luckily, we're a much bigger community made of open minded people who do not work on products just for fame and glory, but because we believe on missions and visions of our own dreams.

And people like you are the kind of toxic players this community is trying to push out the window. Learn to behave in the FOSS, we're not your slaves. Baseline of discussions is based on licenses and trademarks, if there's none registered all is left is "mutual agreements" which might or might not happen. That's how life works.

**Comment by Dazag** [comment]
Alright mate, I hope I have never have to work on anything with people like you, it will just bring shit to my place. I just imagine myself doing something like that, so when I am all famous and the OS becomes competitive (after thousands of hours of work) then all programmers want to come and write code and do things their way because is FOSS I have nothing to say about it? Yeah, laws are a clear definition of what you should or shouldn't do, that's why all of you know all the laws and never break any. BTW Linus Trovalds has been the biggest asshole in the whole internet in many occasions, why do you think is that? Because incompetent people think they have better ideas of what Linux should be, compared to his.

**Comment by Werner1201** [comment]
This issue is a joke, all of this just because "users will think that this is 'official'" "let's prevent problems". Now this thread shows up on Google's news feed as some sort of shitshow. Gnu/Linux community in a nutshell

**Comment by StarrKiss** [comment]
Lmao this is bullshit. I hate it when people wave copyright law in others faces over circumstances where it doesn't even apply! This'd be like Microsoft trying to sue someone for calling a FOSS software "windows tweaks", and at least there they'd have the money to sue any developer to oblivion. Stop going on your useless power trip @cassidyjames

**Comment by tomascohen** [comment]
Yeah, let's put some TNT to burn the bridges down and end any possible cooperation with the people behind the project you love and use.
Nice community building move.

**Comment by krisives** [comment]
@tomascohen FWIW it's been very clear that I don't share the same vision that the elementaryOS developers do. We fundamentally disagree on basic principles of FOSS and the basic rights to copy/redistribute software. Their vision is everyone pays for a `.iso` download and anyone who shares a link to it gets banned, despite them building everything using Debian/Ubuntu using those rights to redistribute that were afforded to them.

That bridge was long burned before this!

I wish the eOS developers the best of luck, but their strategy for attracting or keeping app developers or at least porting apps to their AppCenter has failed abysmally. After approaching a decade there are currently about 50 apps total in AppCenter. I can literally fit them all in a single screenshot:

![image](https://user-images.githubusercontent.com/153967/131607099-f522962a-1663-4c70-92db-465c749b7fb3.png)

**Comment by pedro2555** [comment]
I've signed up on the phone just to attempt to bring reason here.

I'm a proud paying user of Elementary OS.

The request made to this project was a honest attempt at avoiding confusion. Is simple to follow, it does not jeopardize this project in anyway.

The honest way to reject this request is indeed to realize the diferences and divert to an appropriate channel for such discussion.

This is no legal matter, and to the extend that it is, this business of attacking with legal documents to non-legal professionals does not help any of the causes.

I do believe all parties make valid points of concern and that they should, to the best of their abilities, address them on appropriate terms; and that may mean a compromise.

Please be respectufull that someone else might disagree with your point of view, that does not make it any more valid or invalid, it just means they disagree. Find the terms where you agree with as a starting point, rather than the other way around.

What would the developers of this project suggest as an alternative to what is requested as to address the requester's concerns, may I ask?

**Comment by julianxhokaxhiu** [comment]
> What would the developers of this project suggest as an alternative to what is requested as to address the requester's concerns, may I ask?

I fully agree with your view and I think a reasonable compromise should be found for the best of both parties, especially if this projects aim to support its own user base which targets the product under dispute.

I'm pretty sure the main dev is welcome for any of that change, all is trying to empathize though is the fact that a simple request escalated into "legal terms" and then waterfall-ed into a blame circle of who owns what. As always in life bad misunderstanding sometimes leads to big clashes.

Given the premises though, I think the suggestion by @AdrianVovk `extras-for-elementary-os` fits perfectly this project target goal, and naming change would not be confusing yet provide context to the end goal. For the best of both parties, I think an outcome to this issue should be found, even if the issue is now officially closed.

**Comment by jtremback** [comment]
IANAL but this whole thing is incredibly stupid. Trademarks can exist whether they are registered or not. The registration is just extra proof. Obviously, Elementary OS has a trademark on Elementary whether it's registered or not. 

All of the self-righteous fluff about the GPL is completely unrelated and irrelevant. That's copyright, not trademark.

**Comment by krisives** [comment]
Hi @jtremback. I believe you're reading a separate article and posting to this discussion. The two are separate.

**Comment by Exagone313** [comment]
I would suggest closing and locking this issue. It won't be fixed. If the so-called trademark owner has a legal complaint to fill, let them do it. You should not discuss the subject publicly. Ask for advice to a lawyer.

**Comment by krisives** [comment]
> You should not discuss the subject publicly

I encourage others to have the discussion publicly.

**Comment by zsvicvk** [comment]
Let's dispel some myths.

---

@julianxhokaxhiu "You clearly have never understood what working on FOSS means."

Here's a quote from the GPL v3:

> Notwithstanding any other provision of this License, for material you add to a covered work, you may (if authorized by the copyright holders of that material) supplement the terms of this License with terms:
>
>    a) Disclaiming warranty or limiting liability differently from the terms of sections 15 and 16 of this License; or
>
>    b) Requiring preservation of specified reasonable legal notices or author attributions in that material or in the Appropriate Legal Notices displayed by works containing it; or
>
>   c) Prohibiting misrepresentation of the origin of that material, or requiring that modified versions of such material be marked in reasonable ways as different from the original version; or
>
>    d) Limiting the use for publicity purposes of names of licensors or authors of the material; or
>
>    e) Declining to grant rights under trademark law for use of some trade names, trademarks, or service marks; or
>
>    f) Requiring indemnification of licensors and authors of that material by anyone who conveys the material (or modified versions of it) with contractual assumptions of liability to the recipient, for any liability that these contractual assumptions directly impose on those licensors and authors.

That's right, the GPL explicitly allows trademark restrictions, and for a good reason, the same reason we have trademark laws in the first place.

"Baseline of discussions is based on licenses and trademarks, if there's none registered all is left is "mutual agreements" which might or might not happen." — Under trademark law, even unregistered trademarks carry legal protection. Only active use in commerce is required for legal protection.

---

@StarrKiss "I hate it when people wave copyright law in others faces over circumstances where it doesn't even apply!" — It does apply, read GPL quote above.

---

@krisives "We fundamentally disagree on basic principles of FOSS and the basic rights to copy/redistribute software." — Trademark protection is explicitly allowed in the GPL, for good reason. See quote above.

Also it's funny you bring up Debian and Ubuntu, since they have the same restrictions on using their trademarks:

> When You Can NEVER Use the Debian Trademarks Without Asking Permission
>
> You cannot use Debian trademarks in any way that suggests an affiliation with or endorsement by the Debian project or community, if the same is not true.
>
>You cannot use Debian trademarks in a company or organization name or as the name of a product or service.
>
> https://www.debian.org/trademark

--

> You cannot use the Trademarks in software titles. If you are producing software for use with or on Ubuntu you may reference Ubuntu, but must avoid: (i) any implication of endorsement, or (ii) any attempt to unfairly or confusingly capitalise on the goodwill of Canonical or Ubuntu.
>
> https://ubuntu.com/legal/intellectual-property-policy

**Comment by krisives** [comment]
@zsvicvk Debian actually has a trademark registered though

[86037470.pdf](https://github.com/krisives/elementary-os-extras/files/7110440/86037470.pdf)

**Comment by zsvicvk** [comment]
@krisives Once again, trademarks do not need to be registered for them to receive legal protections under law.

**Comment by krisives** [comment]
I guess everyone registering trademarks is just getting scammed out of their money since there is no reason. :rofl:

**Comment by zsvicvk** [comment]
@krisives Not my fault you don't understand trademark law. There are real benefits to having it registered, listed here: https://www.uspto.gov/trademarks/basics/why-register-your-trademark, however it is not required for protection against infringement.

**Comment by krisives** [comment]
@zsvicvk From the link you provided to the USPTO:

> If you haven’t filed for state or federal registration, your trademark protection is based solely on using your trademark in commerce within a particular geographic area.

**Comment by zsvicvk** [comment]
Yep. What about it? elementary does business in the US, and the trademark is used in the US, so it has protection in that geographic area (the US).

And not to miss the broader point, that preventing unauthorized use of the project's name is standard practice in any major Free Software project. It's nothing unique or new.

**Comment by krisives** [comment]
At best Elementary, Inc. (which isn't the same as Elementary, LLC) does business out of one or two states. This is the reason that trademarks are registered federally. It's okay that you don't understand trademark law.

**Comment by zsvicvk** [comment]
"your trademark protection is based solely on using your trademark in commerce within a particular geographic area."

***Using***. Wherever the trademark is ***used***, protection applies. It is used across the US.

**Comment by krisives** [comment]
Commerce is defined as where they accept and trade goods, which they do from a single (or possibly a few) states, eg. where their accounts are located and their taxes are filed.

**Comment by krisives** [comment]
Also very interesting that people are registering brand new GitHub accounts to avoid commenting on this issue with their real accounts. Fascinating.

**Comment by amsicam** [comment]
Selling to people in a US state counts as "use in commerce" there. See https://www.finnegan.com/en/insights/articles/use-in-commerce-problems-in-u-s-trademark-cases.html for examples, including an interesting case where a Canadian company managed to get "use in commerce" in the US just because some people from the US were their customers, even though they had no US locations at all!

At any rate, your claims about preventing misuse of trademarks is somehow incompatible with Free Software philosophy is just downright incorrect. Read the GPL.

**Comment by Werner1201** [comment]
Open Source Community, where you are free to develop and name your project, unless if I don't like it. 

Despite of the very bad joke I made, I think this issue could have been much more productive if the Author just asked by premisses of good will, without that copyright and trademark discussion. If he just opened the issue and just asked for the change of name and explained that by changing it the owner of the repo and the author would receive a lot less miscommunication in issues I think it would lead to another outcome that would be less of a shitshow. Oh well, C'est la vie.

**Comment by lcrippa** [comment]
Years ago, on the very first installation of Debian I performed, I added the repo debian-multimedia, thinking it was an official repository for multimedia packages. Well, it wasn't and after some time on sid it made an unholy mess of conflicts.  First lesson learned, DontBreakDebian. 
That repo still exists, but it is now called "deb-multimedia", presumably after some controversy ensued. I think I wouldn't have added it if the name didn't imply it was part of the official debian project.
All the debate on the tone of the original request and on the nuances of trademark law (and even on the definition of "commerce") is not really useful. 
Naming a repo "$OS-extras" is not the best choice, because people who don't know better might assume it is officially supported as, for example, non-free or multiverse. 
Of course you can name your repo as you like, and clearly people add it at their own risk. 
Changing the name to something like "extras-for-$OS", as suggested above, would however be the common sense thing to do

**Comment by krisives** [comment]
My guess is that you lacked the understanding of how to manage packages and instead of running a few basic commands to resolve the dependency errors you declared it "broke" and re-installed. Cool story, though, thanks?

>  All the debate on the tone of the original request and on the nuances of trademark law (and even on the definition of "commerce") is not really useful.

When the request originally came in it was under the guise of "see our branding page" with a link to their company website and a heavy emphasis on trademarks. After I look up a trademark filed by said company the message becomes "you're doxxing me privately!!!!111"

>  Naming a repo "$OS-extras" is not the best choice, because people who don't know better might assume it is officially supported as, for example, non-free or multiverse.

This assumes that people are adding PPAs by just trying random combinations of characters in the command line. They'll learn about the PPA from this page or one of the upstream `README.md` files from one of the programs that are packaged here just like one of the dozens of other programs I package and maintain.

**Comment by lcrippa** [comment]
Well, you guessed wrong, it took me a day but i resolved all the conflicts by hand and learned a lot in the process.
Again, I'm not debating the tone of the messages and how the conversation spun out of control because it is not relevant to the point, I won't judge the personalities of the people involved.
Some people will learn from the README, some others might learn from a semi-wrong post in a forum or on an advice by someone random, and in general the direction of an independent repo relies only on the mantainer and is uncorrelated to the official project.
Again, you can call the repo whatever you want. Calling it something else is generally the more prudent solution and could be considered kind, but nobody is forcing you. All the doxxing-trademark stuff is rather cringy from all sides and frankly beside the point

**Comment by krisives** [comment]
> Well, you guessed wrong, it took me a day but i resolved all the conflicts by hand and learned a lot in the process.

Wow, PPAs must be great then :rofl:
